Add SBOM jsf signing to openjdk_build_pipeline.groovy
adoptium/ci-jenkins-pipelines pull request #1131
Opened 2024-10-30 17:24 UTC by Haroon-Khel

ref https://github.com/adoptium/temurin-build/issues/3946

Code to run the (incomplete) https://ci.adoptium.net/job/build-scripts/job/release/job/sign_temurin_jsf/ job which signs the SBOM using https://github.com/adoptium/temurin-build/blob/master/cyclonedx-lib/sign_src/TemurinSignSBOM.java

On line 1866 it should archive the `temurin-sign-sbom.jar` so that it can be used later to sign the SBOM on the eclipse worker node. The artifact should get copied over during the sign_temurin_jsf job

Lines 1057 to 1094 is just the gpgSign() function repeated for thesign_temurin_jsf job

This pr is together with https://github.com/adoptium/temurin-build/pull/4017

2024-11-06 21:51 UTC, sophia-guo commented
Could this be done at post build stage as initially we tried to do this in post stage but due to the PEM issue it's blocked. i.e, to sign all sbom files at the post stage. https://github.com/adoptium/ci-jenkins-pipelines/pull/739/files

2024-12-03 06:53 UTC, karianna commented
@Haroon-Khel linter failures

2024-12-03 10:50 UTC, andrew-m-leonard requested changes

2024-12-03 10:50 UTC, andrew-m-leonard commented on pipelines/build/common/openjdk_build_pipeline.groovy
> +    // Kick off the sign_temurin_jsf job to sign the SBOM
From the JSON vs XML discussion we've just had, we probably ought to call this job something slightly different... maybe simply sign_SBOM...

For the moment, we can have the XML discussion before we decide.

2024-12-10 03:06 UTC, karianna approved these changes

2024-12-12 10:14 UTC, andrew-m-leonard commented on pipelines/build/common/openjdk_build_pipeline.groovy
> +                    filter: '**/*.sig',
This should be the SBOM json file

2024-12-12 10:14 UTC, andrew-m-leonard commented on pipelines/build/common/openjdk_build_pipeline.groovy
> +                        context.archiveArtifacts artifacts: 'workspace/target/*.sig'
JSF Signature is in the SBOM json, that needs archiving

2024-12-17 14:02 UTC, Haroon-Khel commented
Well that was a terrible attempt at a rebase. Trying again

2024-12-19 09:32 UTC, andrew-m-leonard commented on pipelines/build/common/openjdk_build_pipeline.groovy
> +    // Kick off the sign_temurin_jsf job to sign the SBOM
using JSON signing for the moment

2024-12-19 09:33 UTC, andrew-m-leonard requested changes
needs updates to job params

2024-12-23 12:14 UTC, Haroon-Khel commented
Using the`update branch` button on github did a better rebase than any of my attempts

2024-12-24 11:27 UTC, Haroon-Khel commented
> needs updates to job params

@andrew-m-leonard was this resolved with the rebase?

2025-01-02 09:01 UTC, andrew-m-leonard approved these changes

2025-01-02 10:56 UTC, merged