Only enable sanity.openjdk tests to hotspot jdk8 s390
adoptium/ci-jenkins-pipelines pull request #141
Opened 2021-05-03 20:46 UTC by sophia-guo

Add the ability to specify test list according to vendor or impl

Fix #116 

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

2021-05-04 09:13 UTC, M-Davies requested changes
Groovy lint
```
2021-05-03 22:34:10 [INFO]   File:[pipelines/build/common/build_base_file.groovy]
2021-05-03 22:34:16 [ERROR]   Found errors in [npm-groovy-lint] linter!
2021-05-03 22:34:16 [ERROR]   Error code: 1. Command output:
------
GroovyLint: Started CodeNarc Server
/github/workspace/pipelines/build/common/build_base_file.groovy
  220   error    Unexpected input: '{
            def testJobType = "nightly"
            if (releaseType.equals("Weekly") || releaseType.equals("Release")) {
                testJobType = "weekly"
            }
            if (isMap(configuration.test)) {
                if (configuration.test.containsKey(variant)) {
                    //Test is enable for the variant
                    if (configuration.test.get(variant)) {
                        def testObj = isMap(configuration.test.get(variant)
                        if (' @ line 220, column 28.  NglParseError   
```

2021-05-04 14:22 UTC, sophia-guo commented
run tests

2021-05-04 15:00 UTC, sophia-guo commented
run tests

2021-05-04 15:38 UTC, sophia-guo commented
run tests

2021-05-04 16:47 UTC, sophia-guo commented
run tests

2021-05-04 19:49 UTC, sophia-guo commented
run tests

2021-05-04 19:56 UTC, sophia-guo commented
Test build: https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/build-test/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-hotspot/3/console

2021-05-04 21:30 UTC, M-Davies requested changes
Couple of styling recommendations

2021-05-04 21:30 UTC, M-Davies commented on README.md
> +| test                       | ❌    | `String`<br>**OR**<br>`Map<String, List>`<br>**OR**<br>`Map<String, List or Map<String, List>>`   | Case one: tests to run against the binary after the build has
```suggestion
| test                       | ❌    | `String`<br>**OR**<br>`Map<String, List>`<br>**OR**<br>`Map<String, Map<String, List>>`   | Case one: Tests to run against the binary after the build has completed. A `default` tag indicates that you want to run [whatever the default test nightly/release list is](https://github.com/adoptium/ci-jenkins-pipelines/blob/ab947ce6ab0ecd75ebfb95eb2f75facb83e4dc13/pipelines/build/common/build_base_file.groovy#L66-L88).<br><br>Case two: You can also [specify your own list for that particular platform (not variant)](https://github.com/adoptium/ci-jenkins-pipelines/blob/ab947ce6ab0ecd75ebfb95eb2f75facb83e4dc13/pipelines/jobs/configurations/jdk16_pipeline_config.groovy#L59-L64). <br><br>Case three: Or you can even specify the list for that particular platform per variant. The list could be specific one `sanity.openjdk` or `default` (similar to the first case) or a map per nightly or release (similar to case two).
```

2021-05-05 13:58 UTC, sophia-guo commented on README.md
> +| test                       | ❌    | `String`<br>**OR**<br>`Map<String, List>`<br>**OR**<br>`Map<String, List or Map<String, List>>`   | Case one: tests to run against the binary after the build has
Updated. Thanks!

2021-05-05 14:47 UTC, M-Davies approved these changes
LGTM. Thanks for doing those changes

2021-05-11 19:02 UTC, smlambert approved these changes

2021-05-11 19:02 UTC, merged