add support for building Bisheng JDK8/11 on Linux_x64/aarch64
adoptium/ci-jenkins-pipelines pull request #144
Opened 2021-05-07 12:38 UTC by eapenzhan

@sxa Since bisheng jdk 8/11 is supported by the build farm on Linux_x64/aarch64, we hope they can also be added to the pipeline. Could you help me for this?

2021-05-07 15:46 UTC, M-Davies commented
run tests

2021-05-07 18:09 UTC, M-Davies requested changes
Code LGTM but I think you have to accept the license agreement before you can commit this PR

2021-05-08 01:38 UTC, eapenzhan commented
Thank you. I've agreed.

2021-05-08 09:51 UTC, M-Davies approved these changes

2021-05-18 10:39 UTC, karianna approved these changes
lgtm

2021-05-18 10:39 UTC, merged