Enable bisheng risc-v from jdk11u nightly build through cross-compile
adoptium/ci-jenkins-pipelines pull request #148
Opened 2021-05-20 02:07 UTC by feilongjiang

https://github.com/adoptium/temurin-build/pull/2616/commits has been merged. This pr enables bishengjdk-11 risc-v nightly build.

I can not access the Adotpium CI systems, so this pr is not tested yet.

Questions: in temurin-build, I have added `BUILD_CC` and `BUILD_CXX` as configuring args, are they needed in pipeline jobs `configureArgs`?

2021-05-20 12:30 UTC, karianna approved these changes
LGTM

2021-05-20 13:35 UTC, sxa commented
> Question: in temurin-build, I have added `BUILD_CC` and `BUILD_CXX` as configuring args, are they needed in pipeline jobs `configureArgs`?

I don't believe so - we haven't had to use those variables anywhere else (so far).

2021-05-20 17:00 UTC, sxa requested changes
Unnecessary commas. I will aim to approve tomorrow. I want to hold off on merging until we can test it during the day (UK time, since that's where most of the people doing builds are!) Hopefully we can get this merged and tested tomorrow.

I've been able to successfully build Bisheng with the cross-compiler we use so hopefully this won't be problematic

2021-05-21 08:10 UTC, sxa approved these changes

2021-05-21 08:10 UTC, merged