add support for adoptium/jdk11u-fast-startup-incubator project
adoptium/ci-jenkins-pipelines pull request #257
Opened 2022-03-02 08:05 UTC by kelthuzadx

Hi there! We have created a fast startup project(https://github.com/adoptium/jdk11u-fast-startup-incubator) under adoptium group to explore some novel JVM startup technilogies. I also create a simple build pipeline(x64_linux) for it. This build pipeline is currently hosted on http://ci.dragonwell-jdk.io/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-fast_startup/, which is a fork of the official adoptium pipeline(https://github.com/adoptium/ci-jenkins-pipelines / https://ci.adoptopenjdk.net/). I want to try to move it to official adoptium CI platform(https://ci.adoptopenjdk.net/) and host on that. Please let me know your advice and thoughts, thanks in advance!

2022-03-02 12:47 UTC, karianna approved these changes
Looks OK but holding off merging until temurin-build PR is good.

2022-03-02 16:36 UTC, sophia-guo commented
Is the project interested in the test run? I mean if the project build would run smoke tests and aqa tests? If it's yes, then probably other changes needed.

2022-03-03 02:38 UTC, kelthuzadx commented
> Is the project interested in the test run? I mean if the project build would run smoke tests and aqa tests? If it's yes, then probably other changes needed.

Hi @sophia-guo, this project only runs JDK jtreg tests. The purpose of this project is to explore some HotSpot techniques(Pre-initialization for CDS and static analysis based on that, etc), currently only jtreg tests are added/modified.

2022-03-04 11:46 UTC, sxa commented
Related PR is now merged.

2022-03-04 13:11 UTC, sxa requested changes
I'm absolutely 👍🏻 on this but don't want to do it on a Friday in the absence of anyone likely to run this through a test pipeline before the weekend runs, so I'm rejecting purely to avoid anyone merging this today ;-)

2022-03-07 10:22 UTC, sxa approved these changes

2022-03-07 10:22 UTC, merged