Don't add whitespace if no existing configure args
adoptium/ci-jenkins-pipelines pull request #287
Opened 2022-04-28 01:47 UTC by AdamBrousseau

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

2022-04-28 01:48 UTC, AdamBrousseau commented
We had an odd bug on our builds where a single configure arg was prefixed with a whitespace. This caused some parsing of that arg to fail. This fix will only add the whitespace if args already exist.

2022-05-02 06:27 UTC, zdtsw reviewed
LGTM

2022-05-02 10:31 UTC, karianna requested changes
LGTM

2022-05-02 10:31 UTC, karianna approved these changes

2022-05-03 15:26 UTC, sophia-guo approved these changes

2022-06-08 11:33 UTC, zdtsw approved these changes

2022-06-08 11:54 UTC, merged