feat: enable --create-sbom (in temurin-build) by passing new flag into BUILD_ARGS
adoptium/ci-jenkins-pipelines pull request #297
Opened 2022-05-16 14:15 UTC by zdtsw

- enable all OS except Windows(under test) and AIX(fix javac)

2022-05-16 14:32 UTC, karianna requested changes
My understanding is that SBOM only works for Java 19+. Or is that just the reproducible builds feature of that?

2022-05-16 18:32 UTC, andrew-m-leonard commented
@zdtsw So there is no reason the SBOM feature can't be used for all the versions, although it's intended purpose is to work along side reproducible builds. Reproducible builds is currently jdk-19, and also jdk-17 in the near future (possibly 17.0.4).

From a pure SSDF point of view we want to use it for all versions.

2022-05-16 18:34 UTC, andrew-m-leonard approved these changes

2022-05-16 18:36 UTC, andrew-m-leonard commented
> My understanding is that SBOM only works for Java 19+. Or is that just the reproducible builds feature of that?

@karianna I think you maybe thinking of the build-script changes to enable reproducible builds that require jdk-19+ due to requirement for the bootjdk jar -date option which only exists in jdk-19 and jdk-17.0.3. SBOM support is actually independent of this.

2022-05-17 15:07 UTC, karianna approved these changes

2022-05-17 15:07 UTC, merged