feat: support to copy/archive openjdk_pipeline back to weekly-pipeline
adoptium/ci-jenkins-pipelines pull request #326
Opened 2022-06-15 08:02 UTC by zdtsw

As one step to get the artifacts we can use for comparison. various solutions we can use to store build artifacts: 

- upload to GH repository, 
- archive in Jenkins, 
- upload to 3rd party storage(e.g S3)

this PR is to use what we already have as Jenkins space, and it is not supposed to cause disk issue, because this only happens on weekly-pipeline build + only upload successful downstream openjdk-pipeline artifacts.

Ref https://github.com/adoptium/ci-jenkins-pipelines/issues/301

2022-06-15 08:47 UTC, karianna requested changes

2022-06-15 08:57 UTC, zdtsw commented on pipelines/build/common/weekly_release_pipeline.groovy
> +    //if releaseType=Release: Copy artifacts from downstream and archive again
updated with inline comments

2022-06-18 12:42 UTC, karianna approved these changes

2022-06-27 07:59 UTC, andrew-m-leonard approved these changes

2022-06-27 12:19 UTC, karianna commented on pipelines/build/common/weekly_release_pipeline.groovy
> +    // For reproduciable builds (releaseType==Release) to have comparision on multiple builds' artifacts
```suggestion
    // For reproducible builds (releaseType==Release) to have comparison on multiple builds' artifacts.
```

2022-06-27 12:19 UTC, karianna commented on pipelines/build/common/weekly_release_pipeline.groovy
> +    // Copy artifacts from downstream and archive again on weekly-pipeline. Detail see issue: https://github.com/adoptium/ci-jenkins-pipelines/issues/301
```suggestion
    // Copy artifacts from downstream and archive again on weekly-pipeline. For details, see issue: https://github.com/adoptium/ci-jenkins-pipelines/issues/301
```

2022-06-27 12:29 UTC, merged