feat: add Jenkinsfile for comparision job
adoptium/ci-jenkins-pipelines pull request #327
Opened 2022-06-15 15:27 UTC by zdtsw

Add new Jenkinsfile for a new job to do simple comparision of two downloadable tar ball

Ref https://github.com/adoptium/ci-jenkins-pipelines/issues/301

2022-06-18 12:44 UTC, karianna reviewed
The comparison tool is diff - does that go deep enough?

2022-06-18 12:45 UTC, karianna requested changes

2022-06-18 12:45 UTC, karianna commented on tools/reproduce_comparison/Jenkinsfile
> +        string(name: 'URL1', defaultValue: '', description: 'URL to one versoin of the build artifacts\ne.g: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk18-pipeline/lastSuccessfulBuild/a
```suggestion
        string(name: 'URL1', defaultValue: '', description: 'URL to one version of the build artifacts\ne.g.: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk18-pipeline/lastSuccessfulBuild/artifact/target/linux/x64/temurin/OpenJDK18U-jdk_x64_linux_hotspot_2022-06-11-23-30.tar.gz')
```

2022-06-18 12:45 UTC, karianna commented on tools/reproduce_comparison/Jenkinsfile
> +        string(name: 'URL2', defaultValue: '', description: 'URL to the other versoin of the build artifacts\ne.g: https://github.com/adoptium/temurin19-binaries/releases/download/jdk-2022-06-09-19-1
```suggestion
        string(name: 'URL2', defaultValue: '', description: 'URL to the other version of the build artifacts\ne.g.: https://github.com/adoptium/temurin19-binaries/releases/download/jdk-2022-06-09-19-11-beta/OpenJDK-jdk_x64_linux_hotspot_2022-06-09-03-31.tar.gz')
```

2022-06-18 14:28 UTC, zdtsw commented
> The comparison tool is diff - does that go deep enough?
diff 
```
-r, --recursive
              recursively compare any subdirectories found
```

````
$ diff -q -r wen1 wen2
Files wen1/filewen11 and wen2/filewen11 differ
Only in wen2/folderwen11: filefolder11
Only in wen2/folderwen11: folderwen12



$ tree wen1
wen1
├── filewen11
├── filewen12
└── folderwen11
    ├── filefolderwen11
    └── filefolderwen12

1 directory, 4 files



$ tree wen2
wen2
├── filewen11
├── filewen12
└── folderwen11
    ├── filefolder11
    ├── filefolderwen11
    ├── filefolderwen12
    └── folderwen12

2 directories, 5 files
```

2022-06-23 15:42 UTC, sxa reviewed
This seems to do a `cleanWs()` before the comparison but is it going to leave the artifacts around once finished? Sine this can execute on any machine labelled linux it's going to leave lots of stuff around on all of those machines I believe, which is undesirable.

2022-06-23 15:59 UTC, zdtsw commented
> This seems to do a `cleanWs()` before the comparison but is it going to leave the artifacts around once finished? Sine this can execute on any machine labelled linux it's going to leave lots of stuff around on all of those machines I believe, which is undesirable.

can add another cleanws() then the job is done, maybe better to cleanup space?

2022-06-27 12:50 UTC, andrew-m-leonard approved these changes

2022-06-27 12:50 UTC, merged