fix: link reference in architecture
adoptium/ci-jenkins-pipelines pull request #482
Opened 2022-11-01 03:40 UTC by sakshi1215

Signed-off-by: Sakshi Patle <sakshi.patle121@gmail.com>
fixes https://github.com/adoptium/ci-jenkins-pipelines/issues/447

2022-11-01 03:42 UTC, sakshi1215 commented
@adamfarley @smlambert please review

2022-11-07 11:13 UTC, zdtsw commented on docs/ARCHITECTURE.md
> +of this code is defined in [openjdk_build_pipeline.groovy](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/).
any reason to remove openjdk_build_pipeline.groovy from the change?

2022-11-07 17:27 UTC, adamfarley commented
In #447 I advised using a relative path to prevent this issue happening in the future. 

Another (better?) option would be to replace everything above the top-level directory with a forward slash (so https://github.com/user/repo/folder/folder2/filename.txt becomes /folder/folder2/filename.txt).

2022-11-07 17:32 UTC, adamfarley requested changes
Ditto zdtsw's comment. Also, in https://github.com/adoptium/ci-jenkins-pipelines/issues/447 I advised using a relative path to prevent this issue happening in the future.

Another (better?) option would be to replace everything above the top-level directory with a forward slash (so https://github.com/user/repo/folder/folder2/filename.txt becomes /folder/folder2/filename.txt).

2022-11-11 16:35 UTC, sakshi1215 commented
> Ditto zdtsw's comment. Also, in #447 I advised using a relative path to prevent this issue happening in the future.
> 
> Another (better?) option would be to replace everything above the top-level directory with a forward slash (so https://github.com/user/repo/folder/folder2/filename.txt becomes /folder/folder2/filename.txt).

I thought it is not a good practice to use relative paths for the actively changing repositories, I prefer relative path for docs repositories where you know you won't be messing around with the structure quiet often. But for code absolute path seems more declarative as well as is more descriptive the next time you make changes in your code directories. I may be wrong too but just laying out my opinions @adamfarley .

2022-11-14 11:29 UTC, adamfarley commented
> > Ditto zdtsw's comment. Also, in #447 I advised using a relative path to prevent this issue happening in the future.
> > Another (better?) option would be to replace everything above the top-level directory with a forward slash (so https://github.com/user/repo/folder/folder2/filename.txt becomes /folder/folder2/filename.txt).
> 
> I thought it is not a good practice to use relative paths for the actively changing repositories, I prefer relative path for docs repositories where you know you won't be messing around with the structure quiet often. But for code absolute path seems more declarative as well as is more descriptive the next time you make changes in your code directories. I may be wrong too but just laying out my opinions @adamfarley .

Sounds sensible. Good reasoning. :)

Looks like we'll be good to go once you've resolved zdtsw's comment.

2023-03-20 17:10 UTC, gdams commented on docs/ARCHITECTURE.md
> +of this code is defined in [openjdk_build_pipeline.groovy](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/).
```suggestion
of this code is defined in [openjdk_build_pipeline.groovy](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy).
```

2023-03-20 17:11 UTC, gdams approved these changes

2023-03-21 07:14 UTC, karianna approved these changes

2023-03-21 07:14 UTC, karianna commented on docs/ARCHITECTURE.md
> +Documentation for this process can be found at [regeneration docs](https://github.com/adoptium/i-jenkins-pipelines/tree/master/pipelines/build/regeneration)
```suggestion
Documentation for this process can be found at [regeneration docs](https://github.com/adoptium/ci-jenkins-pipelines/tree/master/pipelines/build/regeneration)
```

2023-03-29 13:39 UTC, adamfarley approved these changes
LGTM. Merging.

2023-03-29 13:39 UTC, merged