feat: add function for generate release pipeline
adoptium/ci-jenkins-pipelines pull request #517
Opened 2022-11-28 11:58 UTC by zdtsw

Generate new seed jobs in Jenkins

release-build-pipeline-generator: to create release pipeline "release-openjdkX-pipeline" with mini input parameters required by official release build
release_pipeline_jobs_generator_jdkXu: to create downstream build jobs "release-jdkXu---"
fixes: [#3163](https://github.com/adoptium/temurin-build/issues/3163)

2022-11-30 09:26 UTC, karianna requested changes
I've started with the syntax feedback but will take a more in depth look the next review :-)

2022-11-30 09:26 UTC, karianna commented on pipelines/jobs/configurations/jdk11u_release.groovy
> +targetConfigurations = [
The whitespace formatting is different than the other files.  I don't mind which one but we should probably be consistent :-)

2022-11-30 09:57 UTC, zdtsw commented on pipelines/build/common/config_regeneration.groovy
> +        Boolean prBuilder,
renamed to `isPRBuilder`

2022-11-30 10:47 UTC, andrew-m-leonard approved these changes
Looks good I think

2022-12-02 07:13 UTC, zdtsw commented
@karianna can I have another round of review on this PR? thanks!

2022-12-02 08:01 UTC, karianna approved these changes
LGTM, minor suggestions

2022-12-02 08:01 UTC, karianna commented on pipelines/build/regeneration/release_pipeline_generator.groovy
> +// Calling release-pipeline_jobs_generator_jdk11X per each jdk version listed in releaseVersions
```suggestion
// Calling release-pipeline_jobs_generator_jdk<version> per each jdk version listed in releaseVersions
```

2022-12-02 08:01 UTC, karianna commented on pipelines/jobs/configurations/jdk17u_release.groovy
> +return this
```suggestion

return this
```

2022-12-02 08:12 UTC, zdtsw commented on pipelines/build/regeneration/release_pipeline_generator.groovy
> +                def target
i can take another look in this when i work on "prototype" pipeline

2022-12-02 08:22 UTC, merged