update: remove aarch32 jdk8 from release-pipeline default setting
adoptium/ci-jenkins-pipelines pull request #525
Opened 2022-12-02 14:52 UTC by zdtsw

some more for the release pipeline
	- do not have aarch32 in the same batch of build by release-openjdk8-pipeline due to different scmReference
	- good to manually trigger that release by sharing the same pipeline with other jdk8 targets
	- make additionalConfigureArgs only set for jdk11+, default to ' '

Ref: https://github.com/adoptium/ci-jenkins-pipelines/issues/514

2022-12-03 02:14 UTC, karianna requested changes
Are the docs updated to reflect how to run this arm32 Java 8 build separately during a release cycle?

2022-12-03 02:14 UTC, karianna commented on pipelines/build/regeneration/release_pipeline_generator.groovy
> +                if(${javaVersion} != "8") { // for jdk11+, need extra config args to pass down
Maybe that should be >= 11?

2022-12-03 06:30 UTC, zdtsw commented
> Are the docs updated to reflect how to run this arm32 Java 8 build separately during a release cycle?

I have a draft PR https://github.com/adoptium/temurin-build/pull/3159/files for all the changes we make for next release. 
Still more things to be added for "auto" trigger and some.

2022-12-04 04:03 UTC, karianna approved these changes
LGTM assuming the arm32 docs/instructions get landed at the same time

2022-12-04 07:50 UTC, zdtsw commented
> LGTM assuming the arm32 docs/instructions get landed at the same time

docs will be merged before 2023 Jan release as new instruction of how to generate/use/trigger release pipelines.

2022-12-06 08:46 UTC, andrew-m-leonard approved these changes

2022-12-06 09:01 UTC, merged