Update x64 Mac build jobs to use macos11 label
adoptium/ci-jenkins-pipelines pull request #825
Opened 2023-10-10 15:31 UTC by Haroon-Khel

In light of https://github.com/adoptium/infrastructure/issues/2536#issuecomment-1697270848 and https://github.com/adoptium/temurin-build/issues/3354, and now that https://github.com/adoptium/temurin-build/pull/3492 is in we can force the builds to run on Macos11 machines only. 

I am positive I have updated the correct files, but feel free to correct me if so. 

There is one problem. This line, https://github.com/adoptium/ci-jenkins-pipelines/blob/5fcae13f466c8063ca572eaa8365c13548fede46/pipelines/build/common/config_regeneration.groovy#L465, will insist that the `NODE_LABEL` contains the architecture of the binary to build, in this case `x64`. So the final label will be `"NODE_LABEL": "macos11&&build&&mac&&x64"` which will prevent it from running on our arm mac build machines. 

An easy solution is to add `x64` labels to our build arm mac machines. A harder solution is to modify https://github.com/adoptium/ci-jenkins-pipelines/blob/5fcae13f466c8063ca572eaa8365c13548fede46/pipelines/build/common/config_regeneration.groovy#L46 to something more versatile which will not break the other build jobs, but at the moment I do not know this repo well enough for this to be a quick fix before the next release. 

@sxa @andrew-m-leonard thoughts?

2023-10-10 16:01 UTC, sxa requested changes
I don't think this will work - it'll look for [macos11&&build&&mac&&x64](https://ci.adoptium.net/label/macos11&&build&&mac&&x64/) (which we don't have any of) instead of selecting an aarch64 build machine

2023-10-10 16:05 UTC, sxa commented
Take a look at the `crossCompile` sections in jdk11u for 32-bit arm and riscv64 for an example of how to make it run on a different machine. Hopefully something that that will work here too.

2023-10-12 12:14 UTC, Haroon-Khel commented
>Take a look at the crossCompile sections in jdk11u for 32-bit arm and riscv64 for an example of how to make it run on a different machine. Hopefully something that that will work here too.

I have added `x64` labels to the build-arm-mac machines so they now show up in https://ci.adoptium.net/label/macos11&&build&&mac&&x64/. Let's merge this pr and if we see stable builds then I can implement a more versatile solution

2023-10-12 12:42 UTC, sxa approved these changes
While it's not ideal having that label on a machine that is of a different architecture I'll approve this on the basis that this is an interim solution for next week's release and we will look at doing it properly for the next release. Let's also make sure that when we merge this we take the build label OFF the x64 ones (and log here which machines that's been done on) to ensure that we don't end up with a random selection of x64 or aarch64 systems used for builds which could affect reproducibility

2023-10-12 12:59 UTC, andrew-m-leonard commented
I think we might be able to use the crossCompile option, eg: https://github.com/adoptium/ci-jenkins-pipelines/blob/633cb3dd440b6b0d69301e91dd258d764cb0073a/pipelines/jobs/configurations/jdk21u_pipeline_config.groovy#L179
?

2023-10-12 14:59 UTC, Haroon-Khel commented
@andrew-m-leonard Right now ive labelled our build-arm-mac machines with `x64` so this will allow the arm mac build jobs to run on these machines. This is only a temp solution to see if we get a stable run of nightlies, and then I can implement a more long term solution using https://github.com/adoptium/ci-jenkins-pipelines/blob/633cb3dd440b6b0d69301e91dd258d764cb0073a/pipelines/jobs/configurations/jdk21u_pipeline_config.groovy#L179

You should know that with this pr merged only build-macstadium-macos11-arm64-1 and build-macstadium-macos11-arm64-2 will be used for building arm and x64 mac for the major jdk versions. I believe testing will still be done both the x64 and arm64 test machines

2023-10-13 10:01 UTC, Haroon-Khel commented
I just remembered, for cross compiling jdk11+ the `--openjdk-target=x86_64-apple-darwin` needs to be added to the configure args, so we can merge this until changes are added for this

2023-10-13 10:22 UTC, sxa commented
> I just remembered, for cross compiling jdk11+ the `--openjdk-target=x86_64-apple-darwin` needs to be added to the configure args,

Oh https://github.com/adoptium/temurin-build/pull/3492/files was only doing the change for JDK8 - ok in that case I guess we'll bee need another temurin-build PR for 11+.

> we can merge this until changes are added for this

Should that be "can't"?

2023-10-13 10:29 UTC, Haroon-Khel commented
>Should that be "can't"?

Havent had my coffee this morning 😅 

>Oh https://github.com/adoptium/temurin-build/pull/3492/files was only doing the change for JDK8 - ok in that case I guess we'll bee need another temurin-build PR for 11+.

On it

2023-10-13 10:50 UTC, Haroon-Khel commented
https://github.com/adoptium/temurin-build/pull/3502 is ready to review

2023-10-13 15:01 UTC, andrew-m-leonard approved these changes

2023-10-13 15:11 UTC, sxa commented
/approve

2023-10-13 15:12 UTC, merged