Tagbuilds
adoptium/ci-jenkins-pipelines pull request #914
Opened 2024-02-05 12:52 UTC by andrew-m-leonard

Provides tag driven builds for all jdk versions, main & evaluation
Scheduled builds disabled

Fixes: https://github.com/adoptium/ci-jenkins-pipelines/issues/902

2024-02-05 15:12 UTC, andrew-m-leonard commented
run tests

2024-02-05 16:54 UTC, andrew-m-leonard commented
run tests

2024-02-05 16:58 UTC, andrew-m-leonard commented
run tests

2024-02-06 03:50 UTC, karianna commented
pipeline-build-check failed in part because the jdk8 pipeline was on a host that ran out of space.

2024-02-06 09:06 UTC, andrew-m-leonard commented
> pipeline-build-check failed in part because the jdk8 pipeline was on a host that ran out of space.

yep, I think @steelhead31 's hopefully fixed it, i'll re-trigger

2024-02-06 09:06 UTC, andrew-m-leonard commented
run tests

2024-02-06 09:49 UTC, karianna requested changes
Not so sure on the commented out code, would prefer to see it deleted I think (Git will let us get it back)

2024-02-06 13:58 UTC, andrew-m-leonard commented
> Not so sure on the commented out code, would prefer to see it deleted I think (Git will let us get it back)

@karianna yes, agree, better to delete the lines

2024-02-06 15:05 UTC, andrew-m-leonard commented
run tests

2024-02-06 16:24 UTC, andrew-m-leonard commented
run tests

2024-02-07 10:19 UTC, sxa reviewed
Initial comment before I properly analyse the code - can we add some end-user information on this new process into https://github.com/adoptium/ci-jenkins-pipelines/blob/master/README.md where we describe the current nightly triggering.

2024-02-07 10:28 UTC, sxa commented
> > Not so sure on the commented out code, would prefer to see it deleted I think (Git will let us get it back)
> 
> @karianna yes, agree, better to delete the lines

In this case I'd actually prefer to have them present and commented out so it's obvious where the time-based scheduling can be re-enabled if desired. We will presumably still need this functionality for new releases while they are maintained by Oracle and not getting regular tags.

I guess as a middle ground we could just leave it in the JDK22+ ones if you don't want to retain it for all of them.

2024-02-07 11:05 UTC, sxa reviewed
The logic SGTM subject to my limited groovy expertise ... Most of the things in here are queries and doc suggestions that it would be nice to have answers to prior to giving a formal approval but it looks like you've done some testing on it so it should be good. We'll see if there are any other edge cases we've missed once it goes live, but this should be a lot nicer than my original prototype code that we've been relying on for a few months!

2024-02-07 11:21 UTC, andrew-m-leonard commented
> Initial comment before I properly analyse the code - can we add some end-user information on this new process into https://github.com/adoptium/ci-jenkins-pipelines/blob/master/README.md where we describe the current nightly triggering.

thanks for pointing out, yes updated

> Initial comment before I properly analyse the code - can we add some end-user information on this new process into https://github.com/adoptium/ci-jenkins-pipelines/blob/master/README.md where we describe the current nightly triggering.

thanks for pointing out, updated and added description of pipeline groovy and parameters

2024-02-07 11:22 UTC, andrew-m-leonard commented
> > > Not so sure on the commented out code, would prefer to see it deleted I think (Git will let us get it back)
> > 
> > 
> > @karianna yes, agree, better to delete the lines
> 
> In this case I'd actually prefer to have them present and commented out so it's obvious where the time-based scheduling can be re-enabled if desired. We will presumably still need this functionality for new releases while they are maintained by Oracle and not getting regular tags.
> 
> I guess as a middle ground we could just leave it in the JDK22+ ones if you don't want to retain it for all of them.

Yes, i've added back in as a comment for jdk22.groovy, which will be used as a basis for jdk22u.groovy which will required the schedule

2024-02-07 11:36 UTC, sxa commented
Raised [question in slack](https://adoptium.slack.com/archives/C09NW3L2J/p1707305735196349?thread_ts=1707235495.875719&cid=C09NW3L2J) about whether there might be a better name than `main` for the non-evaluation pipelines (especially since `main` is now used by github as the default branch in new repositories) but that shouldn't be considered a blocker from my pespective

2024-02-07 11:43 UTC, andrew-m-leonard commented on pipelines/build/common/build_base_file.groovy
> -        // Definition of filenames when building an EA tag. This is passed
you're welcome :-)

2024-02-07 11:47 UTC, andrew-m-leonard commented on pipelines/build/common/trigger_beta_build.groovy
> +        def additionalConfigureArgs =  (version > 8) ? "--with-version-opt=ea" : "--with-milestone=beta"
yeah I specified it for jdk8 just so it's clear, but I think you're right

2024-02-07 11:59 UTC, andrew-m-leonard commented on pipelines/build/common/trigger_beta_build.groovy
> +    def buildTag=latestAdoptTag.replaceAll("_adopt","-ea-beta")
yeah, i'm changing that to be clearer. Build tag is the binaries repo release tag. It is in fact the publishJobTag which then has "-beta" appended by the publish job: https://github.com/adoptium/github-release-scripts/blob/2e8dea702fda98c23a52eb436d1927261d29b0d1/sbin/Release.sh#L165

2024-02-07 19:25 UTC, karianna approved these changes

2024-02-07 19:26 UTC, merged

2024-02-07 19:26 UTC, karianna commented on README.md
> +All JDK versions now support "beta" EA triggered builds from the publication of upstream build tags. Eclipse Adoptium no
had a typo so I didn't commit that.